# Generated by Django 4.2.6 on 2023-11-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_alumnos_alter_curso_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(blank=True, null=True, related_name='alumnos', to='cursos.alumno'),
        ),
    ]
